import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import topGradient from '../public/top-gradient.svg'
import Navbar from '../components/Navbar/Navbar'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <img src={topGradient.src} alt="top gradient" className={styles.topGradient} />
      <Head>
        <title>Matsuel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />


    </div>
  )
}

export default Home
